#    █████╗  █████╗ ███╗   ███╗███╗   ███╗ █████╗ ███╗  ██╗██████╗ ██╗      █████╗  ██████╗  ██████╗ ███████╗██████╗
#   ██╔══██╗██╔══██╗████╗ ████║████╗ ████║██╔══██╗████╗ ██║██╔══██╗██║     ██╔══██╗██╔════╝ ██╔════╝ ██╔════╝██╔══██╗
#   ██║  ╚═╝██║  ██║██╔████╔██║██╔████╔██║███████║██╔██╗██║██║  ██║██║     ██║  ██║██║  ██╗ ██║  ██╗ █████╗  ██████╔╝
#   ██║  ██╗██║  ██║██║╚██╔╝██║██║╚██╔╝██║██╔══██║██║╚████║██║  ██║██║     ██║  ██║██║  ╚██╗██║  ╚██╗██╔══╝  ██╔══██╗
#   ╚█████╔╝╚█████╔╝██║ ╚═╝ ██║██║ ╚═╝ ██║██║  ██║██║ ╚███║██████╔╝███████╗╚█████╔╝╚██████╔╝╚██████╔╝███████╗██║  ██║
#    ╚════╝  ╚════╝ ╚═╝     ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚══╝╚═════╝ ╚══════╝ ╚════╝  ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝

# ----------------------------------------------------------------------------------------------------------------------


bot-token: ''

channels:
  887161863480172544:
    commands:
      - "/gamemode"
      - "/gamerule"
      - "/difficulty"
    message: "**{player}** used the command `{command}`."

